export type CoreDraftBlockType =
  | "header-one"
  | "header-two"
  | "header-three"
  | "header-four"
  | "header-five"
  | "header-six"
  | "section"
  | "article"
  | "unordered-list-item"
  | "ordered-list-item"
  | "blockquote"
  | "atomic"
  | "code-block"
  | "unstyled";
